version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 463470960120.dkr.ecr.us-east-1.amazonaws.com
      - echo Logged in to Amazon ECR successfully

  build:
    commands:
      - echo Building Docker Image for Flask Application
      - docker build -t flask_image .
      - echo Image built successfully
      # - python -m pytest --junitxml=pytest_reports/pytest_report.xml

  post_build:
    commands:
      - echo Tagging Flask Docker image
      - docker tag flask_image:latest 463470960120.dkr.ecr.us-east-1.amazonaws.com/flask_image:latest
      - docker push 463470960120.dkr.ecr.us-east-1.amazonaws.com/flask_image:latest
      - echo Flask image pushed to ECR
      - echo "we are in the build block"
      - echo "we will run some tests"
      - grep -Fq "EC2" homepage.html
# reports:
#   pytest_reports:
#     files:
#       - pytest_report.xml
#     base-directory: pytest_reports/
#     file-format: JUNITXML
    
artifacts:
  files:
    - 'scripts/**/*'
    - 'appspec.yml'
